version = 1

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["react"]
  environment = [
    "nodejs",
    "mongo"
  ]

[[analyzers]]
name = "docker"

  [analyzers.meta]
  dockerfile_paths = ["dockerfile"]